name: my_tool_kit
description: "A new Flutter package project."
version: 0.0.2
homepage:

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # 永久储存
  shared_preferences: ^2.2.3
  # 状态管理工具,路由
  get: ^4.6.6
  # 下拉刷新和上拉加载
  easy_refresh: ^3.4.0
  # 权限请求
  permission_handler: ^11.3.1
  # 蓝牙
  flutter_blue_plus: ^1.34.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
